### ISSUE TITLE
Tropical Cyclone Modelling (Phase 4) not working on iOS

### ISSUE THREAD

**Issue by Cruifer** [njsparks/iris#1]
Hi there. I'm opening this issue to tell you that Tropical Cyclone Modelling (Phase 4) is not sending any calculations on iOS devices, therefore the project is currently stuck at 6.03% since 3 weeks now.
This probably isn't the best place to send this feedback but every other way I tried failed.
Also, do we know when Sparks & Toumi (2024) paper will be published?
Thanks

**Comment by njsparks** [comment]
Hello, the paper has been published and I've added links.

The dreamlab team is aware of the issue and hopefully it will be resolved shortly.
